// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fumzfxeikhjedppxnqen.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1bXpmeGVpa2hqZWRwcHhucWVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk1MDQyOTMsImV4cCI6MjA1NTA4MDI5M30._EPXQUGoztsNKxAS1n1Nu2rOhLWyTvUtLbDkxAZ41Co";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);